session_name: cppgram_example
start_directory: ./ # load session relative to config location (project root).
windows:
  - window_name: src
    focus: true
    panes:
      - shell_command: nvim
  - window_name: cppgram
    layout: main-horizontal
    options:
      main-pane-height: 50
    panes:
      - shell_command:
        - nvim -c 'OpenSession cppgram' opt/cppgram
  - window_name: debug
    layout: main-vertical
    panes:
      - shell_command: gdb example
      - shell_command: cat bot.log
  - window_name: docs
    layout: main-horizontal
    options:
      main-pane-height: 50
    panes:
      - shell_command_before:
        - cd opt/cppgram
        - nvim README.md
      - shell_command_before:
        - cd opt/cppgram
        - doxygen
